"""Add Flow Power PEA settings

Revision ID: 546b2ceef0e5
Revises: h1a2b3c4d5e6
Create Date: 2025-12-14 09:37:19.094378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546b2ceef0e5'
down_revision = 'h1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flow_power_base_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pea_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pea_custom_value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pea_custom_value')
        batch_op.drop_column('pea_enabled')
        batch_op.drop_column('flow_power_base_rate')

    # ### end Alembic commands ###
