"""add_daily_and_monthly_supply_charges_to_user_model

Revision ID: 7ba8a45bfd47
Revises: a54dbb75f762
Create Date: 2025-11-25 21:29:42.795925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba8a45bfd47'
down_revision = 'a54dbb75f762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_supply_charge', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monthly_supply_charge', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('monthly_supply_charge')
        batch_op.drop_column('daily_supply_charge')

    # ### end Alembic commands ###
