"""Add automations tables

Revision ID: 87c1f25f657b
Revises: a9e3e737af8c
Create Date: 2026-01-16 12:21:36.215990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c1f25f657b'
down_revision = 'a9e3e737af8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('run_once', sa.Boolean(), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=True),
    sa.Column('notification_only', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('execution_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['automation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=True),
    sa.Column('repeat_days', sa.String(length=20), nullable=True),
    sa.Column('battery_condition', sa.String(length=50), nullable=True),
    sa.Column('battery_threshold', sa.Integer(), nullable=True),
    sa.Column('flow_source', sa.String(length=50), nullable=True),
    sa.Column('flow_transition', sa.String(length=20), nullable=True),
    sa.Column('flow_threshold_kw', sa.Float(), nullable=True),
    sa.Column('price_type', sa.String(length=20), nullable=True),
    sa.Column('price_transition', sa.String(length=20), nullable=True),
    sa.Column('price_threshold', sa.Float(), nullable=True),
    sa.Column('grid_condition', sa.String(length=20), nullable=True),
    sa.Column('weather_condition', sa.String(length=20), nullable=True),
    sa.Column('time_window_start', sa.Time(), nullable=True),
    sa.Column('time_window_end', sa.Time(), nullable=True),
    sa.Column('last_evaluated_value', sa.Float(), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['automation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automation_trigger')
    op.drop_table('automation_action')
    op.drop_table('automation')
    # ### end Alembic commands ###
