"""Add Enphase Enlighten credentials

Revision ID: a9e3e737af8c
Revises: b1u2v3w4x5y6
Create Date: 2026-01-15 14:11:30.510541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e3e737af8c'
down_revision = 'b1u2v3w4x5y6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enphase_username', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('enphase_password', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('enphase_serial', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('enphase_serial')
        batch_op.drop_column('enphase_password')
        batch_op.drop_column('enphase_username')

    # ### end Alembic commands ###
