"""Add ngrok_authtoken_encrypted to User model

Revision ID: b767f7ac4a28
Revises: ab08488206e2
Create Date: 2025-12-12 17:19:27.561247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b767f7ac4a28'
down_revision = 'ab08488206e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ngrok_authtoken_encrypted', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ngrok_authtoken_encrypted')

    # ### end Alembic commands ###
