"""Remove ngrok_authtoken_encrypted column

Revision ID: e510af51951e
Revises: cfb0956f2875
Create Date: 2025-12-12 19:36:17.710970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e510af51951e'
down_revision = 'cfb0956f2875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ngrok_authtoken_encrypted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ngrok_authtoken_encrypted', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
